In [1]:
# import dependancies

import pandas as pd
import yfinance as yf
import datetime as dt
from datetime import date
import os
import json
import csv

# Define file paths
current_dir = os.getcwd()
parent_dir = os.path.dirname(current_dir)
ticker_dir = os.path.join(parent_dir,'stock_scrape_load')
ticker_path = f"{ticker_dir}/top_100_company_tickers.csv"
output_path = os.path.join(parent_dir,'05_michael_test')

In [2]:
goog = yf.Ticker('GOOG')
goog.history(start = '2023-07-11', end = '2023-07-15')

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2023-07-11 00:00:00-04:00,116.760002,118.224998,115.830002,117.709999,18286600,0.0,0.0
2023-07-12 00:00:00-04:00,119.300003,120.959999,119.000000,119.620003,22059600,0.0,0.0
2023-07-13 00:00:00-04:00,121.540001,125.334999,121.059998,124.830002,31535900,0.0,0.0
2023-07-14 00:00:00-04:00,125.129997,127.089996,124.900002,125.699997,20482800,0.0,0.0

In [3]:

# dates = ['2023-07-11','2023-07-12','2023-7-13','2023-07-14' ]

# Define function to grab requested into from yfinance
# This is a modified version of the function from the company_address_pull_nb.ipynb 
def get_info(ticker):
    print("processing... ", ticker)
    company = yf.Ticker(ticker)
    short_name = company.info['shortName']
    long_name = company.info['longName']
    exchange = company.info['exchange']
    prev_close = company.info['previousClose']
    data = {ticker:{
        'shortName':short_name,
        'longName':long_name,
        'exchange':exchange,
        'previousClose':prev_close
    }}
    return(data)

In [4]:
company_info = {}

with open(ticker_path, 'r') as myfile:
    reader = csv.DictReader(myfile)
    for row in reader:
        ticker = row['Ticker']
        try:
            row_data = get_info(ticker)
            company_info.update(row_data)
        except Exception as e:
            print("error processing ", ticker + ":", e)

processing...  AAPL
processing...  MSFT
processing...  GOOG
processing...  AMZN
processing...  NVDA
processing...  TSLA
processing...  BRK-B
processing...  META
processing...  V
processing...  UNH
processing...  LLY
processing...  WMT
processing...  JPM
processing...  JNJ
processing...  XOM
processing...  MA
processing...  PG
processing...  AVGO
processing...  ORCL
processing...  HD
processing...  MRK
processing...  CVX
processing...  KO
processing...  PEP
processing...  ABBV
processing...  COST
processing...  BAC
processing...  ADBE
processing...  MCD
processing...  CSCO
processing...  CRM
processing...  PFE
processing...  TMO
processing...  NFLX
processing...  ABT
processing...  AMD
processing...  DHR
processing...  CMCSA
processing...  TMUS
processing...  NKE
processing...  DIS
processing...  WFC
processing...  TXN
processing...  VZ
processing...  UPS
processing...  PM
processing...  NEE
processing...  RTX
processing...  MS
processing...  INTC
processing...  HON
processing...  BMY
processing...  LOW
processing...  QCOM
processing...  BA
processing...  AXP
processing...  SPGI
processing...  INTU
processing...  CAT
processing...  UNP
processing...  COP
processing...  IBM
processing...  AMAT
processing...  AMGN
processing...  DE
processing...  GE
processing...  LMT
processing...  ISRG
processing...  PLD
processing...  T
processing...  NOW
processing...  SYK
processing...  SBUX
processing...  GS
processing...  ELV
processing...  BLK
processing...  SCHW
processing...  MDLZ
processing...  BKNG
processing...  TJX
processing...  GILD
processing...  ADI
processing...  MMC
processing...  ADP
processing...  AMT
processing...  CVS
processing...  VRTX
processing...  C
processing...  UBER
processing...  LRCX
processing...  CI
processing...  HCA
processing...  MO
processing...  ABNB
processing...  ZTS
processing...  PGR
processing...  PANW
processing...  FI
processing...  REGN
processing...  SO

In [5]:
fieldnames = ["ticker", "shortName", "longName", "exchange", "previousClose"]

output_filename = "company_info.csv"
output_filepath = f"{output_path}{output_filename}"

with open(output_filename, 'w', newline='') as csvfile:
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
    writer.writeheader()
    for ticker, data in company_info.items():
        writer.writerow({"ticker": ticker,
                         "shortName": data.get("shortName", ""),
                         "longName": data.get("longName", ""),
                         "exchange": data.get("exchange", ""),
                         "previousClose": data.get("previousClose", "")})

print("Company data saved as", output_filename)

Company data saved as company_info.csv

In [43]:
goog = yf.Ticker('GOOG')
goog_dl = yf.download('GOOG', start = '2023-07-11', end = '2023-07-15')
goog_dl.head()

[*********************100%***********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2023-07-11,116.760002,118.224998,115.830002,117.709999,117.709999,18286600
2023-07-12,119.300003,120.959999,119.000000,119.620003,119.620003,22059600
2023-07-13,121.540001,125.334999,121.059998,124.830002,124.830002,31535900
2023-07-14,125.129997,127.089996,124.900002,125.699997,125.699997,20482800

In [37]:
tickers = ['AAPL','GOOG','MSFT']
start = '2023-01-01'
end = date.today()
download = yf.download(tickers,start)
download.head()

[*********************100%***********************]  3 of 3 completed

             Adj Close                              Close             \
                  AAPL       GOOG        MSFT        AAPL       GOOG
Date
2023-01-03  124.706833  89.699997  238.460129  125.070000  89.699997
2023-01-04  125.993095  88.709999  228.029114  126.360001  88.709999
2023-01-05  124.656982  86.769997  221.270859  125.019997  86.769997
2023-01-06  129.243622  88.160004  223.878616  129.619995  88.160004
2023-01-09  129.772079  88.800003  226.058365  130.149994  88.800003

                              High                                Low  \
                  MSFT        AAPL       GOOG        MSFT        AAPL
Date
2023-01-03  239.580002  130.899994  91.550003  245.750000  124.169998
2023-01-04  229.100006  128.660004  91.239998  232.869995  125.080002
2023-01-05  222.309998  127.769997  88.209999  227.550003  124.760002
2023-01-06  224.929993  130.289993  88.470001  225.759995  124.889999
2023-01-09  227.119995  133.410004  90.830002  231.240005  129.889999

                                         Open                         \
                 GOOG        MSFT        AAPL       GOOG        MSFT
Date
2023-01-03  89.019997  237.399994  130.279999  89.830002  243.080002
2023-01-04  87.800003  225.960007  126.889999  91.010002  232.279999
2023-01-05  86.559998  221.759995  127.129997  88.070000  227.199997
2023-01-06  85.570000  219.350006  126.010002  87.360001  223.000000
2023-01-09  88.580002  226.410004  130.470001  89.195000  226.449997

               Volume
                 AAPL      GOOG      MSFT
Date
2023-01-03  112117500  20738500  25740000
2023-01-04   89113600  27046500  50623400
2023-01-05   80962700  23136100  39585600
2023-01-06   87754700  26612600  43613600
2023-01-09   70790800  22996700  27369800

In [6]:
symbols = pd.read_csv(ticker_path)